BLOCK = 0
FIRE = 1
WATER = 2
EMPTY = -1
mapa_1 = [
BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, 
BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK 
]
#64x36